collegeapp/urls.py
from django.urls import path
from .views import *


app_name = 'collegeapp'
urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('contact/', ClientContactView.as_view(), name='clientcontact'),
    path('about/', ClientAboutView.as_view(), name='clientabout'),
    path('gallery/', ClientGalleryListView.as_view(),
         name='clientgallerylist'),
    path('services/<int:pk>/', ClientServiceDetailView.as_view(),
         name='clientservicedetail'),
    path('news/', ClientNewsListView.as_view(), name='clientnewslist'),
    path('news/<int:pk>/', ClientNewsDetailView.as_view(),
         name='clientnewsdetail'),
    path('subscriber/', ClientSubscriberView.as_view(),
         name='clientsubscriber'),
]
<html>  
<title>

</html>

collegeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collegeapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collegeapp/models.py
from django.db import models


class Message(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Slider(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='sliders')

    def __str__(self):
        return self.title


class Staff(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='staffs')
    detail = models.TextField(max_length=500)
    facebook = models.CharField(max_length=50)
    twitter = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Service(models.Model):
    title = models.CharField(max_length=200)
    detail = models.TextField(max_length=500)
    icon = models.CharField(max_length=200)
    image = models.ImageField(upload_to='services')

    def __str__(self):
        return self.title


class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Gallery(models.Model):
    image = models.ImageField(upload_to='galleries')
    caption = models.CharField(max_length=50)

    def __str__(self):
        return self.image.url


class News(models.Model):
    title = models.CharField(max_length=50)
    detail = models.TextField()
    author = models.CharField(max_length=50)
    image = models.ImageField(upload_to='blogs')
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

collegeapp/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'message', ]
        widgets = {
            'email': forms.EmailInput(attrs={
            })
        }


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={
                'type': 'email',
                'class': 'text',
                'placeholder': 'enter mail here',
            })
        }

collegeapp/views.py
from django.views.generic import *
from .models import *
from .forms import *


class ClientMixin(object):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sliders'] = Slider.objects.all()
        context['staffs'] = Staff.objects.all()
        context['services'] = Service.objects.all()
        context['news'] = News.objects.all()
        context['subscriberform'] = SubscriberForm
        return context


class ClientHomeView(ClientMixin, TemplateView):
    template_name = 'clienttemplates/clienthome.html'


class ClientContactView(ClientMixin, CreateView):
    template_name = 'clienttemplates/clientcontact.html'
    form_class = ContactForm
    success_url = '/'


class ClientAboutView(ClientMixin, TemplateView):
    template_name = 'clienttemplates/clientabout.html'


class ClientServiceDetailView(ClientMixin, DetailView):
    template_name = 'clienttemplates/clientservicedetail.html'
    model = Service
    context_object_name = 'service'


class ClientNewsListView(ClientMixin, ListView):
    template_name = 'clienttemplates/clientnewslist.html'
    model = News
    context_object_name = 'newslist'


class ClientNewsDetailView(ClientMixin, DetailView):
    template_name = 'clienttemplates/clientnewsdetail.html'
    model = News
    context_object_name = 'newsdetail'


class ClientSubscriberView(ClientMixin, CreateView):
    template_name = 'clienttemplates/clientsubsciber.html'
    form_class = SubscriberForm
    success_url = '/'


class ClientGalleryListView(ClientMixin, ListView):
    template_name = 'clienttemplates/clientgallerylist.html'
    model = Gallery
    context_object_name = 'gallerylist'

templates/clienttemplates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Literacy a Education Category Flat Bootstrap responsive Website Template | Home :: w3layouts</title>
<link href="{% static 'clientstatic/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'clientstatic/js/jquery.min.js' %}"></script>
<!-- Custom Theme files -->
<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'clientstatic/css/lightbox.css' %}" type="text/css" media="all" />

<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Literacy Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- for bootstrap working -->
	<script type="text/javascript" src="{% static 'clientstatic/js/bootstrap.js' %}"></script>
<!-- //for bootstrap working -->
<script src="{% static 'clientstatic/js/responsiveslides.min.js' %}"></script>
<script>
    // You can also use "$(window).load(function() {"
    $(function () {
      // Slideshow 1
      $("#slider1").responsiveSlides({
         auto: true,
		 nav: true,
		 speed: 500,
		 namespace: "callbacks",
      });
    });
  </script>
  <!-- web-fonts -->
  <!-- <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700,600italic,400italic,600,300italic,300,700italic,800,800italic' rel='stylesheet' type='text/css'> -->
	<!-- web-fonts -->
  <script type="text/javascript" src="{% static 'clientstatic/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'clientstatic/js/easing.js' %}"></script>
<!--/script-->
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
</script>
</head>
<body>
	<!-- header-section-starts-here -->
	<div class="header" id="movetop">
		<div class="container">
			<div class="header-top">
				<p><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Phone:+128-546-6853</p>
				<div class="logo">
					<h1><a href="{% url 'collegeapp:clienthome' %}">Sunil Thapa College</a></h1>
				</div>
				<div class="social-icons">
					<ul>
						<li><a class="facebook" href="#"></a></li>
						<li><a class="twitter" href="#"></a></li>
						<li><a class="google-plus" href="#"></a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
			<!-- navigation -->
			<div class="navigation">
					<nav class="navbar navbar-default">
					 
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
						  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						</div>

						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
							  <ul class="nav navbar-nav">
								<li class="{% block home %}{% endblock %}"><a href="{% url 'collegeapp:clienthome' %}">Home <span class="sr-only">(current)</span></a></li>
								<li class="{% block about %}{% endblock %}"><a href="{% url 'collegeapp:clientabout' %}">ABOUT</a>
								
								</li>
								<li class="{% block gallery %}{% endblock %}"><a href="{% url 'collegeapp:clientgallerylist' %}">Gallery</a></li>
								<li class="{% block newslist %}{% endblock %}"><a href="{% url 'collegeapp:clientnewslist' %}">Blog</a></li>
								<li class="{% block contact %}{% endblock %}"><a href="{% url 'collegeapp:clientcontact' %}">Contact Us</a></li>
							  </ul>
						  <div class="clearfix"></div>
						</div><!-- /.navbar-collapse -->
					</nav>
			</div>
			<!-- //navigation -->
		</div>
	</div>
	<!-- header-section-ends-here -->
	
	<!-- content-section-starts-here -->


{% block content %}


{% endblock %}



	<!-- //News-section -->
	<!-- //content-section-ends-here -->
	<!-- footer-section-starts-here -->
	<!-- footer-section -->
	<div class="footer">
		<div class="footer-top">
			<div class="container">
				<div class="col-md-4 footer-grid">
					<h5>NewsLetter</h5>
					<p>Please subscribe here. </p>
					<form method="post" action="{% url 'collegeapp:clientsubscriber' %}">	
					{% csrf_token %}				 
					  <!-- <input type="text" class="text" value="Enter Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Email';}"> -->
					  {{subscriberform.email}}
					 <input type="submit" value="Submit">
					 <div class="clearfix"></div>
				 </form>
				</div>
				<div class="col-md-4 footer-grid">
					<h5>Twitter Feed</h5>
					<p>Check out th best designs online in the world <br>at <a href="mail-to:mail@example.com">http://example.com </a></p>
					<span>1 day ago</span>
					<p><a href="#">Twitter</a>, may be the more visual platform for education group.</p>
					<span>4 day ago</span>
				</div>
				<div class="col-md-4 footer-grid">
					<h5>Follow Us</h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla in purus nibh. Donec ornare felis neque. Nullam tortor! </p>
					
			<div class="social-icons footer-social-icons">
				<a class="facebook" href="#"></a>
				<a class="twitter" href="#"></a>
				<a class="google-plus" href="#"></a>
			</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container">
				<div class="copyrights text-center">
					<p>© 2015 Literacy. All Rights Reserved | Design by   <a href="http://w3layouts.com">  W3layouts</a></p>					
				</div>
				<div class="footer-nav">
					<ul>
						<li><a class="scroll" href="#movetop">Home <span class="sr-only">(current)</span></a></li>
						<li><a href="about.html">ABOUT</a></li>
						<li><a href="typography.html">Short codes</a></li>
						<li><a href="gallery.html">GALLERY</a></li>
						<li><a href="blog.html">Blog</a></li>
						<li><a href="contact.html">Contact Us</a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- //footer-section -->
	<!-- //footer-section-ends-here -->


<script src="{% static 'clientstatic/js/lightbox.js' %}"></script>

	<script type="text/javascript">
		$(document).ready(function() {
				/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
				*/
		$().UItoTop({ easingType: 'easeOutQuart' });
});
</script>
<a href="#to-top" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!----> 

</body>
</html>

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/base.html' %}
{% load static %}

{% block about %}active{% endblock %}

{% block content %}
<div class="content">
		<div class="about-section">
			<div class="about">
				<div class="container">
					<div class="about-top heading">
						<h2 class="heading text-center">ABOUT US</h2>
					</div>
					<div class="about-bottom text-center">
						<img src="{% static 'clientstatic/images/abt.jpg' %}" alt="" />
						<h4>Sed hendrerit dui eget lacus imperdiet lacinia. Sed eleifend, libero ac pellentesque ornare, velit velit tempor nisi, quis cursus dolor velit condimentum elit.</h4>
						<p>Duis semper sodales dictum. Praesent facilisis dui a viverra fringilla. Cras nisi felis, sollicitudin non bibendum iaculis, tincidunt id erat. Morbi tincidunt erat tellus, ut rhoncus sem malesuada et. Duis vitae auctor arcu. Aenean in tellus ac quam maximus dignissim. Vivamus dapibus eget mi ut consectetur. Donec risus nunc, pulvinar eu viverra vitae, placerat at nisi. Duis a mollis enim. Pellentesque sollicitudin dignissim ex, sit amet ornare dui fringilla eu.</p>
					</div>
				</div>
			</div>
		<div class="about-middle">
            <div class="container">
                    <div class="col-lg-4 col-md-6 col-sm-6 testimonials">
                        <h3>Why choose us?</h3>
                        <ul class="list3">
                            <li>
                                <strong>1</strong>
                                <div class="extra">
                                    <p>Cras sagittis tempus ante Curabitur pretium tortor non rhoncus eros orci, ac commodo per, et pret.</p>
                                </div>
                            </li>
                            <li>
                                <strong>2</strong>
                                <div class="extra">
                                    <p>Nam pulvinar tellus vel Morbi quam enim, elementum leo maximus, vitae fermentum nunc ultricies.</p>
                                </div>
                            </li>
                            <li>
                                <strong>3</strong>
                                <div class="extra">
                                    <p>Asety kertya asetli nerafae Proin malesuada porta diam ut ante accumsan, ultricies velit ut, mollis metus.</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6 testimonials">
                        <h3>Special offers</h3>
                        <h4>veriti vitaesaert asrtya aset aplica</h4>
                        <p>Quisque accumsan nulla et velit ullamcortionem ullam corporis suscipit laboriosam, nisi ut aliquid ex.</p>
                        <ul class="list1-2">
                            <li><a href="#">Proin dictum elementum velit</a></li>
                            <li><a href="#">Euismod conseqat ante</a></li>
                            <li><a href="#">Lorem ipsum dolor sit met con</a></li>
                            <li><a href="#">Adipiscing elitlentesque sed dolor</a></li>
                            <li><a href="#">Aliquam congue fermen tum nisl</a></li>
                            <li><a href="#">Mauris accumsan nulla</a></li>
                            <li><a href="#">Sed in lacus ut enim adipiscing</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12 testimonials-box testimonials">
                        <h3>Testimonials</h3>
                        <ul class="list4">
                            <li>
                                <img src="{% static 'clientstatic/images/quote.png' %}" alt="">
                                <div class="extra">
                                    <p>Vestibulum porttitor placerat urna vitae condimentum. Proin consequat Morbi lacinia ipsum ac mi dictum, ac congue odio faucibus. Nam ut pellentesque neque. </p>
                                    <a href="#">Maria Brooks, usa</a>
                                </div>
                            </li>
                            <li>
                                <img src="{% static 'clientstatic/images/quote.png' %}" alt="">
                                <div class="extra">
                                    <p>Vestibulum porttitor placerat urna vitae condimentum. Proin consequat Morbi lacinia ipsum ac mi dictum, ac congue odio faucibus. Nam ut pellentesque neque. </p>
                                    <a href="#">Steven Donovan, usa</a>
                                </div>
                            </li>
                        </ul>
                    </div>
            </div>
    </div>
			<!-- Our-staff-starts -->
		<div class="our-staff about-staff">
			<div class="container">
				<div class="our-staff-head text-center">
					<header>
						<h3>Our Staff</h3>
						<p>Lorem Ipsum is simply dummy Business industry doloremque laudantium.</p>
					</header>
				<div class="our-staff-grids text-center">
					<div class="col-md-3 our-staff-grid">
						<div class="view view-seventh">
								<a href="#"><img class="img-responsive" src="{% static 'clientstatic/images/s1.jpg' %}" alt=""></a>
					                 <div class="mask">
				 						<ul class="staff-social-icons">
											<li><a href="#"><span class="facebook"> </span></a></li>
											<li><a href="#"><span class="twitter"> </span></a></li>
										</ul>
                   					 </div>
                   					 <h4>Doris Wilson</h4>
			                    <p>Sed ut perspiciatis unde omnis iste natus laudantium.</p>
                   		</div>
					</div>
					<div class="col-md-3 our-staff-grid">
						<div class="view view-seventh">
								<a href="#"><img class="img-responsive" src="{% static 'clientstatic/images/s2.jpg' %}" alt=""></a>
					                 <div class="mask">
				 						<ul class="staff-social-icons">
											<li><a href="#"><span class="facebook"> </span></a></li>
											<li><a href="#"><span class="twitter"> </span></a></li>
										</ul>
                   					 </div>
                   					 <h4>Amy Smith</h4>
			                    <p>Sed ut perspiciatis unde omnis iste natus error laudantium.</p>
                   		</div>
					</div>
					<div class="col-md-3 our-staff-grid">
						<div class="view view-seventh">
								<a href="#"><img class="img-responsive" src="{% static 'clientstatic/images/s3.jpg' %}" alt=""></a>
					                 <div class="mask">
				 						<ul class="staff-social-icons">
											<li><a href="#"><span class="facebook"> </span></a></li>
											<li><a href="#"><span class="twitter"> </span></a></li>
										</ul>
                   					 </div>
                   					 <h4>Edna Francis</h4>
			                    <p>Sed ut perspiciatis unde omnis accusantium laudantium.</p>
                   		</div>
					</div>
					<div class="col-md-3 our-staff-grid">
						<div class="view view-seventh">
								<a href="#"><img class="img-responsive" src="{% static 'clientstatic/images/s4.jpg' %}" alt=""></a>
					                 <div class="mask">
				 						<ul class="staff-social-icons">
											<li><a href="#"><span class="facebook"> </span></a></li>
											<li><a href="#"><span class="twitter"> </span></a></li>
										</ul>
                   					 </div>
                   					 <h4>Jennie Crigler</h4>
			                    <p>Sed ut sit voluptatem accusantium doloremque laudantium.</p>
                   		</div>
					</div>
					<div class="clearfix"></div>
				</div>
				</div>
			</div>
		</div>
		<!-- //Our-staff-ends -->
		</div>
	</div>

{% endblock %}

templates/clienttemplates/clientgallerylist.html
{% extends 'clienttemplates/base.html' %}
{% load static %}


{% block gallery %}active {% endblock %}


{% block content %}
	<div class="content">
		<!----> 
<div class="gallery">
		<div class="container">
			<h2 class="heading text-center">Our Classes</h2>
			<div class="gallery-bottom">
				{% for image in gallerylist %}
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="{{ image.image.url }}" data-lightbox="example-set" data-title="{{ image.caption }}"><img class="example-image" src="{{ image.image.url }}" alt=""/></a>
					</div>
					{% endfor %}
					<div class="clearfix"></div>
				</div>
				
		 </div>
	 </div>
<!----> 

	</div>

{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/base.html' %}
{% load static %}

{% block home %}active{% endblock %}

{% block content %}

<div class="slider">
    <ul class="rslides" id="slider1">
    	{% for slider in sliders %}
      <li><img src="{{slider.image.url}}" alt=""></li>
      	{% endfor %}
    </ul>
</div>



	<div class="content">
		<div class="welcome-top">
			<div class="container">
				<div class="col-md-6 welcome_top_left">
					<h3>WELCOME</h3>
					<h5>TO OUR EDUCATION GROUP</h5>
					<p>Lorem Ipsum is simply dummy printing industry. It has survived not. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently.</p>
				</div>
				<div class="col-md-6 welcome_top_right">
					<h3>WE'RE OPEN</h3>
					<h5>In Sed Ut perspiciatis Street</h5>
					<div class="welcome_right_location">
						<div class="location_img">
							<img src="{% static 'clientstatic/images/loc.jpg' %}" alt="" />
						</div>
						<div class="location">
							<p>Lorem Ipsum has been the industry's since the 1500s. It has survived centuries.</p>
							<p class="location_text"><span class="glyphicon glyphicon-map-marker"></span>795 Folsom Ave, Suite 600,San Francisco, CA 94107</p>
							<p class="location_text"><span class="glyphicon glyphicon-dashboard"></span>Mon to Sat 8:30am - 4:30pm,  Sunday - Holiday</p>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="welcome_bottom">
			<div class="container">
				<div class="welcome_head text-center">
					<h2>Welcome To Education Center</h2>
					<p>Neque porro quisquam est, qui dolorem ipsum quia dolor 
					sit amet, consectetur, exercitationem ullam corporis suscipit laboriosam.</p>
				</div>
				<div class="welcome-grids">
					<div class="col-md-6 welcome_bottom_left">
						<img src="{% static 'clientstatic/images/wel.jpg' %}" alt=""/>
					</div>
					<div class="col-md-6 welcome_bottom_right">
						<h3>Sed ut perspiciatis unde omnis iste</h3>
						<p> Quis autem vel eum iure reprehenderit qui 
						in ea voluptate velit esse quam nihil molestiae consequatur, nulla pariatur.
						sit amet, consectetur, adipisci velit, sed quia non numquam. </p>
						<p> Quis autem vel eum iure reprehenderit qui 
						vel illum qui dolorem eum fugiat quo voluptas est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<!-- //welcome -->
		<!-- Our-staff-starts -->
		<div class="our-staff">
			<div class="container">
				<div class="our-staff-head text-center">
					<header>
						<h3>Our Staff</h3>
						<p>Lorem Ipsum is simply dummy Business industry doloremque laudantium.</p>
					</header>
				<div class="our-staff-grids text-center">
					{% for staff in staffs %}
					<div class="col-md-3 our-staff-grid">
						<div class="view view-seventh">
								<a href="#"><img class="img-responsive" src="{{staff.image.url}}" alt=""></a>
					                 <div class="mask">
				 						<ul class="staff-social-icons">
											<li><a target="_blank" href="{{ staff.facebook }}"><span class="facebook"> </span></a></li>
											<li><a target="_blank" href="{{staff.twitter}}"><span class="twitter"> </span></a></li>
										</ul>
                   					 </div>
                   					 <h4>{{staff.name}}</h4>
			                    <p>{{ staff.detail }}</p>
                   		</div>
					</div>
					{% endfor %}
					
					
					
					<div class="clearfix"></div>
				</div>
				</div>
			</div>
		</div>
		<!-- //Our-staff-ends -->
		<!-- Services-starts -->
		<div class="service-section">
				<div class="container">
					<div class="service-section-head text-center">
						<header>
							<h3>Our Services</h3>
							<p>We Provide best you the best services.</p>
						</header>
					</div>
					<div class="service-section-grids">
						{% for service in services %}
						<div class="col-md-4 service-grid">
							<div class="service-section-grid">
								<div class="icon">
									<span style="font-size: 50px;" class="d1 glyphicon glyphicon-{{service.icon}}"></span>
								</div>
								<div class="icon-text">
									<a href="{% url 'collegeapp:clientservicedetail' service.id %}">{{service.title}}</a>
									<p>{{service.detail|truncatechars:"80"}}</p>
								</div>
							</div>
						</div>
							{% endfor %}
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<!-- //services -->
			<!-- News-section -->
			 <div class="news-section">
			 <div class="container">
				<div class="news-section-head text-center">
					<header>
						<h3>Latest News</h3>
						<p>Sed ut perspiciatis unde unde omnis iste natus error totam rem ipsa quae ab illo inventore veritatis</p>
					</header>
				</div>
				<div class="news-section-grids">
					{% for new in news %}
					<div class="col-md-4 news-section-grid">
						<div class="news-section-grid-left">
							<h3>{{new.date|date}}</h3>
						</div>
						<div class="news-section-grid-right">
							<a href="{% url 'collegeapp:clientnewsdetail' new.id %}">{{new.heading}}</a>
							<p>{{new.detail|truncatechars:'80'}} </p>
						</div>
						<div class="clearfix"></div>
					</div>
					{% endfor %}
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/clienttemplates/clientnewslist.html
{% extends 'clienttemplates/base.html' %}
{% load static %}

{% block newslist %}active{% endblock %}

{% block content %}
<div class="content">
		<!-- blogs -->
<div class="blog">
	<div class="container">
		<h2 class="heading text-center">Blogs</h2>
			<div class="single-inline">
				{% for blog in newslist %}
				<div class="col-md-6 blog-to">						
						<a href="{% url 'collegeapp:clientnewsdetail' blog.id %}"><img class="img-responsive sin-on" src="{{ blog.image.url }}" alt="" /></a>
							<div class="blog-top">
							<div class="blog-left">
								<span>{{blog.date}}</span>
							</div>
							<div class="top-blog">
								<a class="fast" href="{% url 'collegeapp:clientnewsdetail' blog.id %}">{{ blog.title }}</a>
								<p>Posted by <a href="{% url 'collegeapp:clientnewsdetail' blog.id %}">{{ blog.author }}</a> in <a href="#">General</a> | <a href="{% url 'collegeapp:clientnewsdetail' blog.id %}">10 Comments</a></p> 
								<p class="sed">{{ blog.detail|truncatechars:"30"}}</p> 
								<a  href="{% url 'collegeapp:clientnewsdetail' blog.id %}" class="more">Readmore<span> </span></a>
								
							</div>
							<div class="clearfix"> </div>
					</div>
					</div>
					{% endfor %}
							
				</div>
				
			</div>
			</div>
	<!-- //blogs -->
	</div>
	<!-- //content-section-ends-here -->





{% endblock %}